//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjoutSupModifPersonnel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommoditeSup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommoditeSup()
        {
            this.DemandeAdmissions = new HashSet<DemandeAdmission>();
        }
    
        public int idCommo { get; set; }
        public string design { get; set; }
        public Nullable<decimal> prix { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeAdmission> DemandeAdmissions { get; set; }
    }
}
